GET http://localhost:9200/_cat/indices?v
###
GET http://localhost:9200/items/_search
###
PUT http://localhost:9200/items
Content-Type: application/json

{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 1
    }
  }
}
###
DELETE http://localhost:9200/items
###